/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scheduletool;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author alish
 */
public class LoadingFrame extends javax.swing.JFrame
    {
    private int count = 0;
    private Border redBorder   = BorderFactory.createLineBorder(Color.RED, 1);
    private Border greenBorder = BorderFactory.createLineBorder(Color.GREEN, 1);    
//--------------------------------------------------------------------------------------------------------------------------------------------
    public LoadingFrame ()
        {
        initComponents ();
        
        loading_Label.setBorder (redBorder);

        }
//--------------------------------------------------------------------------------------------------------------------------------------------
    public void set_label (String label_name)
        {
        if (label_name.equals ("sports"))
            sports_CheckBox.setSelected (true);
        else if (label_name.equals ("leagues"))
            leagues_CheckBox.setSelected (true);        
        else if (label_name.equals ("sportsbooks"))
            sportsbooks_CheckBox.setSelected (true);
        else if (label_name.equals ("schedule"))
            schedule_CheckBox.setSelected (true);
        else if (label_name.equals ("scores"))
            scores_CheckBox.setSelected (true);
        else if (label_name.equals ("league_equivalents"))
            league_equivalents_CheckBox.setSelected (true);
        else if (label_name.equals ("league_teams"))
            league_teams_CheckBox.setSelected (true);
        else if (label_name.equals ("players"))
            players_CheckBox.setSelected (true);
        else if (label_name.equals ("league_players"))
            league_players_CheckBox.setSelected (true);
        else if (label_name.equals ("league_team_players"))
            {
            league_team_players_CheckBox.setSelected (true);

            int delay = 5000; // 5 seconds in milliseconds
            Timer timer = new Timer(delay, (ActionEvent e) -> 
                {
                // Close the frame when the timer triggers.
                dispose();
                });

            // Start the timer.
            timer.setRepeats(false); // Make the timer only trigger once.
            timer.start();            

            loading_Label.setText ("Done Loading");
            loading_Label.setBorder (greenBorder);
            }
        }    
//--------------------------------------------------------------------------------------------------------------------------------------------
    public void relocate ()
        {
        setLocation (Main.schedule_frame.getWidth (), Main.schedule_frame.getY ());
        }
//--------------------------------------------------------------------------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        loading_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sports_CheckBox = new javax.swing.JCheckBox();
        leagues_CheckBox = new javax.swing.JCheckBox();
        sportsbooks_CheckBox = new javax.swing.JCheckBox();
        schedule_CheckBox = new javax.swing.JCheckBox();
        scores_CheckBox = new javax.swing.JCheckBox();
        league_equivalents_CheckBox = new javax.swing.JCheckBox();
        league_teams_CheckBox = new javax.swing.JCheckBox();
        players_CheckBox = new javax.swing.JCheckBox();
        league_players_CheckBox = new javax.swing.JCheckBox();
        league_team_players_CheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loading_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading_Label.setText("Loading...");
        loading_Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sports_CheckBox.setText("Sports");
        sports_CheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sports_CheckBoxActionPerformed(evt);
            }
        });

        leagues_CheckBox.setText("Leagues");

        sportsbooks_CheckBox.setText("Sportsbooks");

        schedule_CheckBox.setText("Schedule");

        scores_CheckBox.setText("Scores");

        league_equivalents_CheckBox.setText("League Equivalents");

        league_teams_CheckBox.setText("League Teams");

        players_CheckBox.setText("Players");

        league_players_CheckBox.setText("League Players");

        league_team_players_CheckBox.setText("League Team Players");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(league_equivalents_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sports_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leagues_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sportsbooks_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schedule_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scores_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(league_teams_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(players_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(league_players_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(league_team_players_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sports_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leagues_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sportsbooks_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schedule_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scores_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(league_equivalents_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(league_teams_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(players_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(league_players_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(league_team_players_CheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loading_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loading_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sports_CheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sports_CheckBoxActionPerformed
    {//GEN-HEADEREND:event_sports_CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sports_CheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox league_equivalents_CheckBox;
    private javax.swing.JCheckBox league_players_CheckBox;
    private javax.swing.JCheckBox league_team_players_CheckBox;
    private javax.swing.JCheckBox league_teams_CheckBox;
    private javax.swing.JCheckBox leagues_CheckBox;
    private javax.swing.JLabel loading_Label;
    private javax.swing.JCheckBox players_CheckBox;
    private javax.swing.JCheckBox schedule_CheckBox;
    private javax.swing.JCheckBox scores_CheckBox;
    private javax.swing.JCheckBox sports_CheckBox;
    private javax.swing.JCheckBox sportsbooks_CheckBox;
    // End of variables declaration//GEN-END:variables
    }
