/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package scheduletool;

/**
 *
 * @author bunny
 */
public class Preset_Message_Dialog extends javax.swing.JDialog
    {
//----------------------------------------------------------------------------------------------------------------------------------------
    private String preset_message;
    private boolean saved;
//----------------------------------------------------------------------------------------------------------------------------------------
    public Preset_Message_Dialog (java.awt.Dialog parent, boolean modal)
        {
        super (parent, modal);
        initComponents ();
        
        setTitle ("Add Preset Message");
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    //initializing fields for when a preset message is added 
    public void initialize_fields_add ()
        {
        setTitle ("Add Preset Message");
        title_Label.setText ("Add Preset Message");
        save_Button.setText ("Add");
        preset_message_TextField.setText ("");
        
        saved = false;
        setVisible (true);
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    //initializes fields for when a preset message is edited 
    public void initialize_fields_edit (String preset_message)
        {
        setTitle ("Edit Preset Message");
        title_Label.setText ("Edit Preset Message");
        save_Button.setText ("Save");
        preset_message_TextField.setText (preset_message);
        
        saved = false;
        setVisible (true);
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    public void add_preset_message ()
        {
        this.preset_message = preset_message_TextField.getText ();
        this.saved = true;
        setVisible (false);
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    public String get_preset_message ()
        {
        return this.preset_message; 
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    public boolean isSaved ()
        {
        return this.saved;
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    public void clear_message ()
        {
        preset_message_TextField.setText ("");
        }
//----------------------------------------------------------------------------------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        title_Label = new javax.swing.JLabel();
        preset_message_TextField = new javax.swing.JTextField();
        clear_message_Button = new javax.swing.JButton();
        save_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        title_Label.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Label.setText("Add Preset Message");
        title_Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 566;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(title_Label, gridBagConstraints);

        preset_message_TextField.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 649;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 6);
        getContentPane().add(preset_message_TextField, gridBagConstraints);

        clear_message_Button.setText("Clear Message");
        clear_message_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clear_message_ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        getContentPane().add(clear_message_Button, gridBagConstraints);

        save_Button.setText("Add Message");
        save_Button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                save_ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 496, 6, 6);
        getContentPane().add(save_Button, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_save_ButtonActionPerformed
    {//GEN-HEADEREND:event_save_ButtonActionPerformed
        // TODO add your handling code here:
        add_preset_message ();
    }//GEN-LAST:event_save_ButtonActionPerformed

    private void clear_message_ButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clear_message_ButtonActionPerformed
    {//GEN-HEADEREND:event_clear_message_ButtonActionPerformed
        // TODO add your handling code here:
        clear_message ();
    }//GEN-LAST:event_clear_message_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
        {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
            {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ())
                {
                if ("Nimbus".equals (info.getName ()))
                    {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                    }
                }
            }
        catch (ClassNotFoundException ex)
            {
            java.util.logging.Logger.getLogger (Preset_Message_Dialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
            }
        catch (InstantiationException ex)
            {
            java.util.logging.Logger.getLogger (Preset_Message_Dialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
            }
        catch (IllegalAccessException ex)
            {
            java.util.logging.Logger.getLogger (Preset_Message_Dialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
            }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
            {
            java.util.logging.Logger.getLogger (Preset_Message_Dialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater (new Runnable ()
            {
            public void run ()
                {
                Preset_Message_Dialog dialog = new Preset_Message_Dialog (new javax.swing.JDialog (), true);
                dialog.addWindowListener (new java.awt.event.WindowAdapter ()
                    {
                    @Override
                    public void windowClosing (java.awt.event.WindowEvent e)
                        {
                        System.exit (0);
                        }
                    });
                dialog.setVisible (true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_message_Button;
    private javax.swing.JTextField preset_message_TextField;
    private javax.swing.JButton save_Button;
    private javax.swing.JLabel title_Label;
    // End of variables declaration//GEN-END:variables
    }
